In [1]:
import numpy as np

In [2]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
b = np.array([1, 2, 3, 4, 5, 6, 7])
a, b

(array([10, 20, 30, 40, 50, 60, 70]), array([1, 2, 3, 4, 5, 6, 7]))

In [3]:
a+b

array([11, 22, 33, 44, 55, 66, 77])

In [4]:
a-b

array([ 9, 18, 27, 36, 45, 54, 63])

In [5]:
a*b

array([ 10,  40,  90, 160, 250, 360, 490])

In [6]:
a/b

array([10., 10., 10., 10., 10., 10., 10.])

In [7]:
a+5

array([15, 25, 35, 45, 55, 65, 75])

In [8]:
a*3

array([ 30,  60,  90, 120, 150, 180, 210])

In [9]:
a/3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        , 23.33333333])

In [10]:
a /= 3 # a = a/3

TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

In [11]:
a = a/3

In [12]:
a

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        , 23.33333333])

In [13]:
arr1 = np.array([ [1],[2],[3] ])
arr1

array([[1],
       [2],
       [3]])

In [14]:
arr2 = np.array([ [1,2,3] ])
arr2

array([[1, 2, 3]])

In [15]:
arr1 + arr2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

### Wybieranie danych z tablicy

In [16]:
np.random.seed(0)
arr = np.random.randint(-10, 11, (7,8) )
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2,  -9,  -4,  -3,   4],
       [  7,  -5,   3,  -2,  -1,  10,   9,   6],
       [  9,  -5,   5,   5, -10,   8,  -7,   7],
       [  9,   9,   9,   4,  -3, -10,  -9,  -1],
       [-10,   0,  10,  -7,   1,   8,  -8, -10],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [17]:
arr[6], arr[-1]

(array([-10,  -6,  -5,  -4,  -2,  10,   7,   5]),
 array([-10,  -6,  -5,  -4,  -2,  10,   7,   5]))

In [19]:
# wiersz 2 i 3, co 3-cia kolumna
arr[ 1:3 , ::3 ]

array([[ 8,  2, -3],
       [ 7, -2,  9]])

In [20]:
# tylko wiersz pierwszy i ostatni
arr[ [0,-1]  ]

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [21]:
arr[ [-1,0]  ]

array([[-10,  -6,  -5,  -4,  -2,  10,   7,   5],
       [  2,   5, -10,  -7,  -7,  -3,  -1,   9]])

In [23]:
# tylko ostatnia kolumna
arr[ : , -1]

array([  9,   4,   6,   7,  -1, -10,   5])

In [26]:
arr.transpose()[-1]

array([  9,   4,   6,   7,  -1, -10,   5])

In [28]:
arr.T[-1]

array([  9,   4,   6,   7,  -1, -10,   5])

In [29]:
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2,  -9,  -4,  -3,   4],
       [  7,  -5,   3,  -2,  -1,  10,   9,   6],
       [  9,  -5,   5,   5, -10,   8,  -7,   7],
       [  9,   9,   9,   4,  -3, -10,  -9,  -1],
       [-10,   0,  10,  -7,   1,   8,  -8, -10],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [30]:
# tylko kolumna nr 2 i przeostania
arr[ : , [1,-2] ]

array([[ 5, -1],
       [-6, -3],
       [-5,  9],
       [-5, -7],
       [ 9, -9],
       [ 0, -8],
       [-6,  7]])

In [36]:
for index in range(arr.shape[0]):
    print(arr[index])
    print("="*40)

[  2   5 -10  -7  -7  -3  -1   9]
[ 8 -6 -4  2 -9 -4 -3  4]
[ 7 -5  3 -2 -1 10  9  6]
[  9  -5   5   5 -10   8  -7   7]
[  9   9   9   4  -3 -10  -9  -1]
[-10   0  10  -7   1   8  -8 -10]
[-10  -6  -5  -4  -2  10   7   5]


In [37]:
for row in arr:
    print(row)
    print("="*40)

[  2   5 -10  -7  -7  -3  -1   9]
[ 8 -6 -4  2 -9 -4 -3  4]
[ 7 -5  3 -2 -1 10  9  6]
[  9  -5   5   5 -10   8  -7   7]
[  9   9   9   4  -3 -10  -9  -1]
[-10   0  10  -7   1   8  -8 -10]
[-10  -6  -5  -4  -2  10   7   5]


### Porównanie szybkości

In [38]:
%%timeit -r 20 -n 500
[x**2 for x in range(1_000)]

371 µs ± 43.4 µs per loop (mean ± std. dev. of 20 runs, 500 loops each)


In [39]:
%%timeit -r 20 -n 500
np.arange(1000)**2

The slowest run took 4.15 times longer than the fastest. This could mean that an intermediate result is being cached.
5.84 µs ± 2.25 µs per loop (mean ± std. dev. of 20 runs, 500 loops each)


In [40]:
371/6

61.833333333333336