In [1]:
import numpy as np

In [2]:
# klaszyczne filtrowanie
number_list = [-20, 20, 10, 100, -30, 1, 2, 5]
[x for x in number_list if x>0]

[20, 10, 100, 1, 2, 5]

In [3]:
arr = np.array(number_list)
arr

array([-20,  20,  10, 100, -30,   1,   2,   5])

In [4]:
arr > 0

array([False,  True,  True,  True, False,  True,  True,  True])

In [5]:
arr[ arr>0 ]

array([ 20,  10, 100,   1,   2,   5])

In [6]:
# >= 10 i <=100
arr[ (arr>=10)&(arr<=100) ]

array([ 20,  10, 100])

In [7]:
# <0 lub >20
arr[ (arr<0)|(arr>20) ]

array([-20, 100, -30])

In [8]:
arr = np.array([-1, 4, np.NaN, 3, np.NaN])
arr

array([-1.,  4., nan,  3., nan])

In [9]:
np.isnan(arr)

array([False, False,  True, False,  True])

In [10]:
arr[ ~np.isnan(arr) ] # ~ - negacja

array([-1.,  4.,  3.])